import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const RESOURCES = [
  // ========== ORIGINALES (33) ==========
  { name: 'Wood', emoji: '🪵', description: 'Madera básica para crafteo inicial.', type: 'material', rarity: 'common', weightKg: 0.5, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Chop en bosque, tierras altas, tundra y cenizales. También como drop de ciertos constructos.', consumeIdea: 'Usar en carpintería para herramientas, armas de asta y estructuras.', sideEffects: 'Ninguno; inflamable cerca del fuego.' },
  { name: 'Pine Cone', emoji: '🌰', description: 'Semilla de pino usada en recetas simples.', type: 'material', rarity: 'rare', weightKg: 0.1, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Gather bajo pinos del bosque y la tundra durante el día.', consumeIdea: 'Triturar para harina de pino o plantar en zonas forestales.', sideEffects: 'Sin riesgo aparente.' },
  { name: 'Apple', emoji: '🍎', description: 'Fruta que recupera un poco de STA.', type: 'consumable', rarity: 'common', weightKg: 0.2, usable: true, effectType: 'sta', effectValue: 5, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Gather en manzanos del bosque y llanuras al amanecer o día.', consumeIdea: 'Comer cruda para aliviar el hambre y recuperar energía.', sideEffects: 'Ninguno.' },
  { name: 'Orange', emoji: '🍊', description: 'Fruta cítrica que recupera STA.', type: 'consumable', rarity: 'uncommon', weightKg: 0.2, usable: true, effectType: 'sta', effectValue: 8, baseValue: 4, stackable: true, maxStack: 99, obtainedFrom: 'Gather en árboles cítricos de bosque, llanuras y oasis del desierto.', consumeIdea: 'Consumir fresca o exprimir en bebida revitalizante.', sideEffects: 'Acidez leve si se abusa.' },
  { name: 'Mango', emoji: '🥭', description: 'Fruta rara que recupera más STA.', type: 'consumable', rarity: 'rare', weightKg: 0.3, usable: true, effectType: 'sta', effectValue: 15, baseValue: 8, stackable: true, maxStack: 99, obtainedFrom: 'Gather en árboles tropicales del bosque en días soleados.', consumeIdea: 'Comer la pulpa para una gran recuperación de vigor.', sideEffects: 'Puede manchar la ropa.' },
  { name: 'Coconut', emoji: '🥥', description: 'Fruta pesada que recupera buena STA.', type: 'consumable', rarity: 'common', weightKg: 0.6, usable: true, effectType: 'sta', effectValue: 12, baseValue: 5, stackable: true, maxStack: 99, obtainedFrom: 'Gather en palmeras costeras y llanuras cálidas.', consumeIdea: 'Beber el agua y comer la pulpa blanca.', sideEffects: 'Cáscara dura; ocupa más espacio en la bolsa.' },
  { name: 'Water', emoji: '💧', description: 'Agua potable para recuperar STA.', type: 'consumable', rarity: 'common', weightKg: 0.3, usable: true, effectType: 'sta', effectValue: 6, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Fish en ríos y lagos; gather junto a fuentes de agua.', consumeIdea: 'Beber para hidratarse y recuperar resistencia.', sideEffects: 'Ninguno.' },
  { name: 'Bamboo', emoji: '🎋', description: 'Material flexible para estructuras ligeras.', type: 'material', rarity: 'uncommon', weightKg: 0.4, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Chop en claros de bosque húmedo y zonas ribereñas.', consumeIdea: 'Tallar cañas de pescar, postes ligeros y arcos primitivos.', sideEffects: 'Resbala si está verde; dejar secar para mayor rigidez.' },
  { name: 'Ancient Wood', emoji: '🪵', description: 'Madera rara de alto valor.', type: 'material', rarity: 'rare', weightKg: 0.8, baseValue: 10, stackable: true, maxStack: 99, obtainedFrom: 'Chop nocturno en bosques antiguos y tierras altas.', consumeIdea: 'Forjar varitas, bastones y empuñaduras épicas.', sideEffects: 'Emite un murmullo leve si se trabaja de noche.' },
  { name: 'Champiñón', emoji: '🍄', description: 'Hongo común con leve recuperación de HP.', type: 'consumable', rarity: 'common', weightKg: 0.1, usable: true, effectType: 'hp', effectValue: 3, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en pantanos y bosques húmedos al atardecer.', consumeIdea: 'Comer crudo para un ligero alivio de heridas.', sideEffects: 'Aroma terroso; algunos ejemplares pueden causar náuseas leves.' },
  { name: 'Baba Verde', emoji: '🟢', description: 'Material viscoso para alquimia.', type: 'material', rarity: 'common', weightKg: 0.3, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Drop de babosas, sapos y criaturas pantanosas.', consumeIdea: 'Base para pociones adhesivas, antídotos y catalizadores.', sideEffects: 'Corrosivo leve para metales; limpiar herramientas tras usarlo.' },
  { name: 'Hierbas', emoji: '🌿', description: 'Planta común de recolección.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras, bosques y orillas de ríos durante el día.', consumeIdea: 'Secar para té medicinal o moler en polvo curativo.', sideEffects: 'Ninguno.' },
  { name: 'Insectos', emoji: '🐛', description: 'Ingrediente común de cebo y recetas.', type: 'material', rarity: 'uncommon', weightKg: 0.05, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Gather nocturno en pantanos, bosques y praderas.', consumeIdea: 'Usar como cebo de pesca o harina proteica.', sideEffects: 'Puede atraer más insectos si se deja al descubierto.' },
  { name: 'Barro', emoji: '🟤', description: 'Base para mezclas y crafteo.', type: 'material', rarity: 'common', weightKg: 0.5, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en pantanos y orillas fangosas de ríos.', consumeIdea: 'Moldear ladrillos, recipientes primitivos y mezclas alquímicas.', sideEffects: 'Moja y ensucia el inventario si no se guarda bien.' },
  { name: 'Champiñón Mágico', emoji: '🪻', description: 'Hongo raro con recuperación alta de HP.', type: 'consumable', rarity: 'rare', weightKg: 0.1, usable: true, effectType: 'hp', effectValue: 25, baseValue: 12, stackable: true, maxStack: 99, obtainedFrom: 'Gather nocturno en bosques profundos y pantanos oscuros.', consumeIdea: 'Consumir para una curación mágica inmediata.', sideEffects: 'Visión ligeramente distorsionada durante unos segundos.' },
  { name: 'Hueso', emoji: '🦴', description: 'Resto ancestral de criaturas antiguas.', type: 'material', rarity: 'rare', weightKg: 0.4, baseValue: 6, stackable: true, maxStack: 99, obtainedFrom: 'Drop de bestias mayores, tumbas y yacimientos fósiles.', consumeIdea: 'Tallar adornos rituales, agujas y componentes nigrománticos.', sideEffects: 'Puede emanar frío residual.' },
  { name: 'Ámbar', emoji: '🟡', description: 'Gema fosilizada de gran valor.', type: 'material', rarity: 'epic', weightKg: 0.2, baseValue: 25, stackable: true, maxStack: 99, obtainedFrom: 'Mine en yacimientos fósiles y árboles petrificados.', consumeIdea: 'Usar en joyería fina y focos arcanos de almacenamiento.', sideEffects: 'Atrae la atención de insectos prehistóricos menores.' },
  { name: 'Ojo Ancestral', emoji: '👁️', description: 'Reliquia legendaria de poder antiguo.', type: 'material', rarity: 'legendary', weightKg: 0.1, baseValue: 50, stackable: true, maxStack: 99, obtainedFrom: 'Drop de jefes antiguos y ruinas selladas.', consumeIdea: 'Canalizar visiones o potenciar rituales de adivinación.', sideEffects: 'Susurros ocasionales; uso prolongado agota la mente.' },
  { name: 'Seda', emoji: '🧵', description: 'Fibra fina para confección.', type: 'material', rarity: 'uncommon', weightKg: 0.1, baseValue: 4, stackable: true, maxStack: 99, obtainedFrom: 'Drop de arañas grandes y gusanos de seda en bosques.', consumeIdea: 'Tejer telas finas, cuerdas ligeras y vendajes.', sideEffects: 'Ninguno.' },
  { name: 'Trigo', emoji: '🌽', description: 'Grano básico de alimento.', type: 'material', rarity: 'common', weightKg: 0.2, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras y granjas abandonadas durante el día.', consumeIdea: 'Moler para harina y hornear pan.', sideEffects: 'Ninguno.' },
  { name: 'Semillas', emoji: '🌱', description: 'Semillas para plantar o procesar.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras, bosques y jardines salvajes.', consumeIdea: 'Plantar cultivos o prensar para aceite.', sideEffects: 'Requieren suelo adecuado para germinar.' },
  { name: 'Hierba', emoji: '🌿', description: 'Hierba común de recolección.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather general en casi todos los biomas diurnos.', consumeIdea: 'Infusiones básicas y componente de vendajes.', sideEffects: 'Ninguno.' },
  { name: 'FlorDragón', emoji: '🌺', description: 'Flor rara con propiedades curativas.', type: 'consumable', rarity: 'rare', weightKg: 0.1, usable: true, effectType: 'hp', effectValue: 15, baseValue: 8, stackable: true, maxStack: 99, obtainedFrom: 'Gather al amanecer o atardecer en llanuras vírgenes.', consumeIdea: 'Masticar los pétalos para cerrar heridas leves.', sideEffects: 'Sabor amargo intenso.' },
  { name: 'Flores', emoji: '🌼', description: 'Flores comunes usadas en preparados.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras, bosques y orillas durante el día.', consumeIdea: 'Elaborar perfumes, tintes y pociones aromáticas.', sideEffects: 'Ninguno.' },
  { name: 'Girasol', emoji: '🌻', description: 'Flor resistente con usos varios.', type: 'material', rarity: 'uncommon', weightKg: 0.15, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras abiertas bajo sol pleno.', consumeIdea: 'Extraer semillas comestibles o aceite.', sideEffects: 'Ninguno.' },
  { name: 'Hierbas Secas', emoji: '🥀', description: 'Fibra vegetal para mezclas y fuego.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en desiertos, tundra y cenizales.', consumeIdea: 'Usar como yesca, relleno de almohadas o té fuerte.', sideEffects: 'Polvorientas; pueden irritar ojos sensibles.' },
  { name: 'Hojas de Viento', emoji: '🍁', description: 'Hoja épica usada en recetas avanzadas.', type: 'material', rarity: 'epic', weightKg: 0.05, baseValue: 20, stackable: true, maxStack: 99, obtainedFrom: 'Gather nocturno en bosques antiguos y cenizales.', consumeIdea: 'Infundir en pociones de velocidad y amuletos de evasión.', sideEffects: 'Zumbido leve en los oídos al manipularlas.' },
  { name: 'Roca Volcánica', emoji: '🪨', description: 'Mineral pesado de zonas volcánicas.', type: 'material', rarity: 'common', weightKg: 1.0, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Mine en volcanes, cenizales y tierras altas.', consumeIdea: 'Moldear muelas, pesas y componentes de hornos.', sideEffects: 'Mantiene calor residual; puede quemar si se toca recién extraída.' },
  { name: 'Cenizas', emoji: '🌫️', description: 'Residuo ligero de origen volcánico.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en volcanes, cenizales y zonas quemadas.', consumeIdea: 'Base para jabón negro, fertilizantes y pigmentos.', sideEffects: 'Polvoriento; ensucia equipo y ropa.' },
  { name: 'Carbón', emoji: '⚫', description: 'Combustible mineral útil en hornos.', type: 'material', rarity: 'uncommon', weightKg: 0.3, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Mine en volcanes, cenizales, tierras altas y cuevas.', consumeIdea: 'Combustible de hornos y forjas; componente de pólvora.', sideEffects: 'Hollina; mancha manos y ropa.' },
  { name: 'Agua', emoji: '💧', description: 'Agua potable para recuperar STA.', type: 'consumable', rarity: 'common', weightKg: 0.3, usable: true, effectType: 'sta', effectValue: 4, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Fish en ríos y lagos; gather junto a manantiales.', consumeIdea: 'Beber para una pequeña recuperación de resistencia.', sideEffects: 'Ninguno.' },
  { name: 'Pez Amarillo', emoji: '🐠', description: 'Pescado común que recupera STA.', type: 'consumable', rarity: 'common', weightKg: 0.3, usable: true, effectType: 'sta', effectValue: 10, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Fish diurno en ríos y lagos.', consumeIdea: 'Asar y comer para recuperar energía.', sideEffects: 'Ninguno.' },
  { name: 'Pez Azul', emoji: '🐟', description: 'Pescado poco común con mejor recuperación de STA.', type: 'consumable', rarity: 'uncommon', weightKg: 0.4, usable: true, effectType: 'sta', effectValue: 18, baseValue: 6, stackable: true, maxStack: 99, obtainedFrom: 'Fish nocturno en ríos profundos y lagos.', consumeIdea: 'Preparar sashimi o caldo nutritivo.', sideEffects: 'Puede contener espinas.' },

  // ========== METALES Y MINERALES ==========
  { name: 'Copper Ore', emoji: '🟤', description: 'Mineral de cobre común. Material base para herramientas y aleaciones.', type: 'material', rarity: 'common', weightKg: 1.1, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Mine en colinas, cuevas y tierras altas.', consumeIdea: 'Fundir en lingotes de cobre para herramientas y joyería básica.', sideEffects: 'Ninguno.' },
  { name: 'Tin Ore', emoji: '⚪', description: 'Mineral de estaño. Se combina con cobre para hacer bronce.', type: 'material', rarity: 'common', weightKg: 1.1, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Mine en colinas rocosas y yacimientos cercanos al agua.', consumeIdea: 'Aleación con cobre para crear bronce.', sideEffects: 'Ninguno.' },
  { name: 'Iron Ore', emoji: '⛓️', description: 'Mineral de hierro pesado. Mina principal para armas y armaduras de bajo nivel.', type: 'material', rarity: 'common', weightKg: 1.4, baseValue: 4, stackable: true, maxStack: 99, obtainedFrom: 'Mine en cuevas, tierras altas y zonas montañosas.', consumeIdea: 'Fundir en lingotes de hierro para armas, armaduras y clavos.', sideEffects: 'Muy pesado; reduce capacidad de carga.' },
  { name: 'Silver Ore', emoji: '🪙', description: 'Mineral de plata brillante. Valioso para joyería y componentes arcanos.', type: 'material', rarity: 'uncommon', weightKg: 1.2, baseValue: 12, stackable: true, maxStack: 99, obtainedFrom: 'Mine en vetas profundas de cuevas y tierras altas.', consumeIdea: 'Refinar en plata para joyas y conductores mágicos.', sideEffects: 'Ninguno.' },
  { name: 'Gold Ore', emoji: '🥇', description: 'Mineral de oro raro. Muy buscado para transacciones y objetos de lujo.', type: 'material', rarity: 'rare', weightKg: 1.3, baseValue: 25, stackable: true, maxStack: 99, obtainedFrom: 'Mine en vetas profundas y lechos de ríos de montaña.', consumeIdea: 'Refinar en lingotes de oro para monedas y adornos.', sideEffects: 'Atrae la atención de bandidos y saqueadores.' },
  { name: 'Platinum Ore', emoji: '🔘', description: 'Mineral de platino resistente. Base de aleaciones épicas y runas poderosas.', type: 'material', rarity: 'epic', weightKg: 1.4, baseValue: 45, stackable: true, maxStack: 99, obtainedFrom: 'Mine en yacimientos profundos de tierras altas y cuevas legendarias.', consumeIdea: 'Fundir para armaduras épicas y runas de alto nivel.', sideEffects: 'Ninguno.' },
  { name: 'Mithril Ore', emoji: '🔷', description: 'Mineral mítico ligero pero resistente. Esencial para equipo de nivel medio-alto.', type: 'material', rarity: 'rare', weightKg: 1.0, baseValue: 22, stackable: true, maxStack: 99, obtainedFrom: 'Mine en cuevas antiguas y ruinas élficas.', consumeIdea: 'Forjar armas y armaduras ligeras de gran resistencia.', sideEffects: 'Ninguno.' },
  { name: 'Adamantite Ore', emoji: '🔶', description: 'Mineral adamantino extremadamente duro. Se extrae de zonas profundas y peligrosas.', type: 'material', rarity: 'epic', weightKg: 1.5, baseValue: 55, stackable: true, maxStack: 99, obtainedFrom: 'Mine en las profundidades de volcanes y mazmorras.', consumeIdea: 'Forjar armas y armaduras de alto nivel casi indestructibles.', sideEffects: 'Requiere herramientas de alto nivel para trabajar.' },
  { name: 'Orichalcum Ore', emoji: '🟣', description: 'Mineral legendario de color cobrizo. Brillo propio, usado en forja de alto nivel.', type: 'material', rarity: 'legendary', weightKg: 1.3, baseValue: 95, stackable: true, maxStack: 99, obtainedFrom: 'Mine en yacimientos míticos y ruinas de civilizaciones perdidas.', consumeIdea: 'Forjar equipo legendario con propiedades mágicas innatas.', sideEffects: 'Emite calor mágico constante.' },
  { name: 'Meteorite Ore', emoji: '☄️', description: 'Fragmento de meteorito caído. Metal celestial con propiedades mágicas desconocidas.', type: 'material', rarity: 'legendary', weightKg: 1.6, baseValue: 120, stackable: true, maxStack: 99, obtainedFrom: 'Recolectar en cráteres y zonas de impacto astral.', consumeIdea: 'Forjar armas celestiales y amuletos de poder cósmico.', sideEffects: 'Radiación arcana leve; puede alterar brújulas mágicas.' },
  { name: 'Obsidian Shard', emoji: '🗿', description: 'Fragmento de vidrio volcánico oscuro. Afilado y usado en rituales y armas.', type: 'material', rarity: 'uncommon', weightKg: 0.8, baseValue: 7, stackable: true, maxStack: 99, obtainedFrom: 'Mine y gather en volcanes y cenizales.', consumeIdea: 'Tallar cuchillas rituales, puntas de flecha y espejos oscuros.', sideEffects: 'Filos extremadamente afilados; riesgo de cortes.' },
  { name: 'Sulfur', emoji: '🟡', description: 'Azufre amarillo volcánico. Ingrediente clave para pólvora y alquimia.', type: 'material', rarity: 'common', weightKg: 0.4, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Mine en volcanes, cenizales y fumarolas.', consumeIdea: 'Componente de pólvora, explosivos y ciertos ácidos alquímicos.', sideEffects: 'Olor acre; irrita ojos y vías respiratorias.' },

  // ========== MADERAS ==========
  { name: 'Birch Log', emoji: '🪵', description: 'Madera de abedul clara y flexible. Se tala en bosques templados.', type: 'material', rarity: 'common', weightKg: 0.8, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Chop en bosques templados y praderas arboladas.', consumeIdea: 'Usar para muebles, herramientas ligeras y papel.', sideEffects: 'Ninguno.' },
  { name: 'Oak Log', emoji: '🪵', description: 'Madera de roble resistente. Material estándar para construcción y armas.', type: 'material', rarity: 'common', weightKg: 1.0, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Chop en bosques y llanuras con robles.', consumeIdea: 'Construcción de escudos, arcos y estructuras robustas.', sideEffects: 'Pesada; requiere más esfuerzo para tallar.' },
  { name: 'Ash Log', emoji: '🪵', description: 'Madera de fresno elástica. Ideal para mangos de herramientas y arcos.', type: 'material', rarity: 'common', weightKg: 0.9, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Chop en bosques húmedos y orillas de ríos.', consumeIdea: 'Fabricar mangos de hacha, arcos cortos y remos.', sideEffects: 'Ninguno.' },
  { name: 'Yew Log', emoji: '🪵', description: 'Madera de tejo densa. Muy valorada para arcos y bastones mágicos.', type: 'material', rarity: 'uncommon', weightKg: 1.0, baseValue: 5, stackable: true, maxStack: 99, obtainedFrom: 'Chop en bosques antiguos y cementerios naturales.', consumeIdea: 'Tallar arcos de larga distancia y bastones de druida.', sideEffects: 'Resina tóxica si se ingiere; usar guantes.' },
  { name: 'Darkwood Log', emoji: '🪵', description: 'Madera oscura del bosque profundo. Absorbe energías arcanas.', type: 'material', rarity: 'rare', weightKg: 1.1, baseValue: 14, stackable: true, maxStack: 99, obtainedFrom: 'Chop nocturno en bosques profundos malditos.', consumeIdea: 'Forjar bastones oscuros y empuñaduras de armas malditas.', sideEffects: 'Absorbe luz; puede volverse más fría al contacto.' },
  { name: 'Ironbark Log', emoji: '🪵', description: 'Corteza férrea casi indestructible. Material legendario para escudos.', type: 'material', rarity: 'epic', weightKg: 1.5, baseValue: 40, stackable: true, maxStack: 99, obtainedFrom: 'Chop en árboles ancianos de tierras altas y bosques legendarios.', consumeIdea: 'Fabricar escudos épicos y armaduras de madera viva.', sideEffects: 'Muy pesada; dificulta el movimiento si se lleva mucha.' },

  // ========== PIELES Y ESCAMAS ==========
  { name: 'Rabbit Pelt', emoji: '🐇', description: 'Piel suave de conejo. Se obtiene de criaturas pequeñas en praderas.', type: 'material', rarity: 'common', weightKg: 0.2, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Drop de conejos y pequeños roedores en llanuras y bosques.', consumeIdea: 'Coser guantes ligeros, forros y amuletos suaves.', sideEffects: 'Ninguno.' },
  { name: 'Wolf Pelt', emoji: '🐺', description: 'Piel de lobo gruesa. Protege contra el frío, usada en armaduras ligeras.', type: 'material', rarity: 'common', weightKg: 0.6, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Drop de lobos en bosques, tundra y tierras altas.', consumeIdea: 'Confeccionar capas, forros de armadura y mantas.', sideEffects: 'Puede conservar olor a lobo; requiere curtido.' },
  { name: 'Boar Hide', emoji: '🐗', description: 'Piel de jabalí resistente. Buena para armaduras de cuero medio.', type: 'material', rarity: 'common', weightKg: 0.9, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Drop de jabalíes en bosques, llanuras y colinas.', consumeIdea: 'Curtir para armadura de cuero resistente y alforjas.', sideEffects: 'Pesada y áspera antes del curtido.' },
  { name: 'Deer Hide', emoji: '🦌', description: 'Cuero de ciervo suave y ligero. Usado en ropa y guantes.', type: 'material', rarity: 'common', weightKg: 0.6, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Drop de ciervos en bosques y llanuras.', consumeIdea: 'Confeccionar guantes, botas ligeras y ropa de viaje.', sideEffects: 'Ninguno.' },
  { name: 'Bear Hide', emoji: '🐻', description: 'Piel de oso gruesa y protectora. Excelente para armaduras pesadas.', type: 'material', rarity: 'uncommon', weightKg: 1.4, baseValue: 8, stackable: true, maxStack: 99, obtainedFrom: 'Drop de osos en bosques profundos y tundra.', consumeIdea: 'Curtir para armaduras pesadas y mantas de supervivencia.', sideEffects: 'Muy pesada; dificulta movimientos rápidos si se usa sin entrenamiento.' },
  { name: 'Wyrm Scale', emoji: '🐉', description: 'Escama de wyrm menor. Brillo metálico, usada en armaduras épicas.', type: 'material', rarity: 'rare', weightKg: 0.8, baseValue: 20, stackable: true, maxStack: 99, obtainedFrom: 'Drop de wyrms menores en tierras altas y cenizales.', consumeIdea: 'Forjar escamas en armaduras de placas ligeras y resistentes.', sideEffects: 'Puede conservar calor residual del dragón.' },
  { name: 'Basilisk Scale', emoji: '🦎', description: 'Escama de basilisco endurecida. Confiere resistencia química al equipo.', type: 'material', rarity: 'epic', weightKg: 1.0, baseValue: 42, stackable: true, maxStack: 99, obtainedFrom: 'Drop de basiliscos en pantanos y ruinas antiguas.', consumeIdea: 'Incorporar en armaduras para resistencia a venenos y ácidos.', sideEffects: 'Contacto prolongado puede entumecer ligeramente la piel.' },

  // ========== TELAS Y FIBRAS ==========
  { name: 'Cotton', emoji: '☁️', description: 'Algodón suave. Se recolecta en praderas para hacer telas básicas.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras y campos de cultivo.', consumeIdea: 'Hilar para telas ligeras, vendajes y ropa interior.', sideEffects: 'Ninguno.' },
  { name: 'Linen Fiber', emoji: '🧵', description: 'Fibra de lino resistente. Material común para ropa y vendajes.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras y jardines abandonados.', consumeIdea: 'Tejer telas frescas y vendajes duraderos.', sideEffects: 'Ninguno.' },
  { name: 'Hemp Fiber', emoji: '🌿', description: 'Fibra de cáñamo áspera. Usada para cuerdas y telas rústicas.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en llanuras, bosques y zonas rurales.', consumeIdea: 'Fabricar cuerdas, redes y telas rústicas.', sideEffects: 'Puede irritar la piel al contacto directo.' },
  { name: 'Silk Fiber', emoji: '🕸️', description: 'Fibra de seda brillante. Se obtiene de arañas y gusanos de seda.', type: 'material', rarity: 'uncommon', weightKg: 0.05, baseValue: 6, stackable: true, maxStack: 99, obtainedFrom: 'Drop de arañas grandes y gusanos de seda en bosques.', consumeIdea: 'Tejer telas finas, cuerdas invisibles y pergaminos lujosos.', sideEffects: 'Ninguno.' },
  { name: 'Shadowweave', emoji: '🖤', description: 'Tejido oscuro que absorbe luz. Material raro para capas y vestimentas de sigilo.', type: 'material', rarity: 'rare', weightKg: 0.1, baseValue: 18, stackable: true, maxStack: 99, obtainedFrom: 'Drop de acechadores sombríos y tejedores nocturnos.', consumeIdea: 'Confeccionar capas de sigilo y bolsas ocultas.', sideEffects: 'Absorbe sonrisas; quien lo lleva parece más pálido.' },
  { name: 'Astral Thread', emoji: '✨', description: 'Hilo tejido con esencia astral. Brilla débilmente, usado en prendas mágicas.', type: 'material', rarity: 'epic', weightKg: 0.05, baseValue: 38, stackable: true, maxStack: 99, obtainedFrom: 'Drop de entidades astrales y constructos arcanos.', consumeIdea: 'Bordar runas en telas y confeccionar vestimentas de hechicero.', sideEffects: 'Brilla débilmente en la oscuridad, revelando al portador.' },

  // ========== HIERBAS Y ALQUIMIA ==========
  { name: 'Nightshade', emoji: '🌑', description: 'Hierba tóxica que crece en sombras. Ingrediente alquímico común.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Gather nocturno en bosques y pantanos sombríos.', consumeIdea: 'Base de venenos, somníferos y tintes oscuros.', sideEffects: 'Tóxica si se ingiere; requiere guantes.' },
  { name: 'Wolfsbane', emoji: '🌿', description: 'Aconito venenoso. Se recolecta en bosques y praderas al anochecer.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Gather al atardecer en bosques y claros de montaña.', consumeIdea: 'Veneno para licántropos y repelente de bestias.', sideEffects: 'Contacto con piel abierta causa entumecimiento.' },
  { name: 'Mandrake Root', emoji: '🪵', description: 'Raíz con forma humanoide. Ingrediente poderoso para pociones y rituales.', type: 'material', rarity: 'uncommon', weightKg: 0.2, baseValue: 8, stackable: true, maxStack: 99, obtainedFrom: 'Gather en bosques antiguos al anochecer; emite un grito al arrancarse.', consumeIdea: 'Potenciar pociones de curación y rituales de resurrección menor.', sideEffects: 'El grito puede aturdir brevemente al recolector.' },
  { name: 'Bloodroot', emoji: '🩸', description: 'Raíz roja sangrante. Usada en pociones de curación y venenos.', type: 'material', rarity: 'uncommon', weightKg: 0.1, baseValue: 7, stackable: true, maxStack: 99, obtainedFrom: 'Gather en pantanos y bosques húmedos.', consumeIdea: 'Base de pociones curativas y venenos hemorrágicos.', sideEffects: 'Tiñe la piel de rojo si se maneja sin guantes.' },
  { name: 'Ghostcap Mushroom', emoji: '🍄', description: 'Hongo translúcido que brilla en la oscuridad. Alucinógeno y mágico.', type: 'material', rarity: 'rare', weightKg: 0.05, baseValue: 15, stackable: true, maxStack: 99, obtainedFrom: 'Gather nocturno en cuevas y bosques profundos.', consumeIdea: 'Infusión ritual para visiones o catalizador de pociones arcana.', sideEffects: 'Alucinaciones leves si se inhala el polvo.' },
  { name: 'Moonpetal', emoji: '🌙', description: 'Pétalo que solo se abre con luna llena. Canaliza energía arcana.', type: 'material', rarity: 'rare', weightKg: 0.02, baseValue: 16, stackable: true, maxStack: 99, obtainedFrom: 'Gather en noches de luna llena en praderas y bosques.', consumeIdea: 'Infundir en pociones de maná y encantamientos lunares.', sideEffects: 'Ninguno si se recoge con cuidado.' },
  { name: 'Dragonleaf', emoji: '🍃', description: 'Hoja con forma de ala de dragón. Aumenta la potencia de pociones.', type: 'material', rarity: 'epic', weightKg: 0.03, baseValue: 35, stackable: true, maxStack: 99, obtainedFrom: 'Gather cerca de guaridas de dragones y tierras altas ardientes.', consumeIdea: 'Catalizador universal para aumentar el efecto de pociones.', sideEffects: 'Puede volver inestable una poción si se usa en exceso.' },
  { name: 'Void Lichen', emoji: '🔮', description: 'Líquen que crece en grietas del plano vacío. Material legendario para alquimia.', type: 'material', rarity: 'legendary', weightKg: 0.02, baseValue: 80, stackable: true, maxStack: 99, obtainedFrom: 'Gather en grietas dimensionales y ruinas del vacío.', consumeIdea: 'Catalizador legendario para pociones de poder inestable.', sideEffects: 'Puede causar mutaciones menores en ingredientes cercanos.' },
  { name: 'Frost Lotus', emoji: '❄️', description: 'Loto helado de la tundra. Mantiene ingredientes estables indefinidamente.', type: 'material', rarity: 'epic', weightKg: 0.05, baseValue: 48, stackable: true, maxStack: 99, obtainedFrom: 'Gather en lagos helados de tundra y cuevas glaciares.', consumeIdea: 'Conservante de pociones y catalizador de magia de hielo.', sideEffects: 'Congela ligeramente lo que toca; usar pinzas.' },
  { name: 'Venom Sac', emoji: '🧪', description: 'Vesícula de veneno extraída de criaturas. Ingrediente para toxinas y antídotos.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Drop de serpientes, arañas y escorpiones.', consumeIdea: 'Crear venenos para armas y antídotos específicos.', sideEffects: 'Puede perforarse fácilmente; manejar con cuidado.' },

  // ========== PARTES DE CRIATURAS ==========
  { name: 'Wolf Fang', emoji: '🦷', description: 'Colmillo de lobo afilado. Usado en amuletos y armas ligeras.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Drop de lobos y caninos salvajes.', consumeIdea: 'Tallar puntas de flecha, amuletos de ferocidad y adornos.', sideEffects: 'Afilado; riesgo de cortes.' },
  { name: 'Boar Tusk', emoji: '🐗', description: 'Colmillo de jabalí curvado. Material para adornos y puntas de lanza.', type: 'material', rarity: 'common', weightKg: 0.2, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Drop de jabalíes y cerdos salvajes.', consumeIdea: 'Tallar puntas de lanza, adornos tribales y sellos.', sideEffects: 'Ninguno.' },
  { name: 'Spider Silk', emoji: '🕸️', description: 'Seda de araña resistente. Alternativa barata a la seda convencional.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Drop de arañas y nidos en bosques y cuevas.', consumeIdea: 'Tejer redes, cuerdas ligeras y vendajes adherentes.', sideEffects: 'Puede pegarse si está húmeda.' },
  { name: 'Bat Wing', emoji: '🦇', description: 'Ala de murciélago seca. Ingrediente para pociones de sonar y rituales.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Drop de murciélagos en cuevas y bosques nocturnos.', consumeIdea: 'Pociones de ecolocalización y polvos volátiles.', sideEffects: 'Olor desagradable si no se seca bien.' },
  { name: 'Bone Dust', emoji: '💀', description: 'Polvo fino de hueso molido. Usado en nigromancia y alquimia oscura.', type: 'material', rarity: 'uncommon', weightKg: 0.1, baseValue: 5, stackable: true, maxStack: 99, obtainedFrom: 'Moler huesos de criaturas y restos ancestrales.', consumeIdea: 'Componente de pociones oscuras, maldiciones y fertilizantes raros.', sideEffects: 'Puede atraer espíritus inquietos.' },
  { name: 'Essence of Shadow', emoji: '🌑', description: 'Esencia condensada de sombra. Drop de criaturas nocturnas y umbrías.', type: 'material', rarity: 'rare', weightKg: 0.02, baseValue: 22, stackable: true, maxStack: 99, obtainedFrom: 'Drop de sombras vivas, espectros y acechadores nocturnos.', consumeIdea: 'Encantar armas de oscuridad y confeccionar capas de sigilo.', sideEffects: 'En exceso, oscurece la piel del portador.' },
  { name: 'Elemental Core', emoji: '🔥', description: 'Núcleo de energía elemental. Drop de elementales y golems.', type: 'material', rarity: 'epic', weightKg: 0.3, baseValue: 50, stackable: true, maxStack: 99, obtainedFrom: 'Drop de elementales de fuego, hielo, tierra y viento.', consumeIdea: 'Alimentar golems, armas elementales y mecanismos arcanos.', sideEffects: 'Puede explotar si recibe un golpe fuerte.' },
  { name: 'Demon Horn', emoji: '😈', description: 'Cuerno de demonio menor. Material legendario para armas y sellos.', type: 'material', rarity: 'legendary', weightKg: 0.6, baseValue: 110, stackable: true, maxStack: 99, obtainedFrom: 'Drop de demonios menores y súcubos.', consumeIdea: 'Forjar armas malditas y sellos de invocación controlada.', sideEffects: 'Corrompe ligeramente el aura del portador.' },

  // ========== GEMAS Y CRISTALES ==========
  { name: 'Quartz Crystal', emoji: '💎', description: 'Cristal de cuarzo común. Conductor básico de energía mágica.', type: 'material', rarity: 'common', weightKg: 0.2, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Mine en cuevas, tierras altas y yacimientos de cristal.', consumeIdea: 'Foco arcano básico y componente de joyería.', sideEffects: 'Ninguno.' },
  { name: 'Amethyst', emoji: '💜', description: 'Gema púrpura brillante. Usada en joyería y focos arcanos.', type: 'material', rarity: 'uncommon', weightKg: 0.1, baseValue: 10, stackable: true, maxStack: 99, obtainedFrom: 'Mine en cuevas profundas y geodas.', consumeIdea: 'Encantar amuletos de claridad mental y joyas.', sideEffects: 'Ninguno.' },
  { name: 'Topaz', emoji: '🧡', description: 'Gema amarilla asociada al fuego y la fuerza. Componente de runas.', type: 'material', rarity: 'rare', weightKg: 0.1, baseValue: 18, stackable: true, maxStack: 99, obtainedFrom: 'Mine en yacimientos volcánicos y geodas de montaña.', consumeIdea: 'Runas de fuerza y armas ígneas.', sideEffects: 'Calienta ligeramente al tacto.' },
  { name: 'Ruby', emoji: '❤️', description: 'Gema roja de fuego vital. Potencia efectos de vida y calor.', type: 'material', rarity: 'rare', weightKg: 0.1, baseValue: 20, stackable: true, maxStack: 99, obtainedFrom: 'Mine en volcanes y cuevas profundas.', consumeIdea: 'Encantamientos de vida y armas de fuego.', sideEffects: 'Puede causar calor excesivo si se combina con fuego.' },
  { name: 'Sapphire', emoji: '💙', description: 'Gema azul del agua y el hielo. Usada en encantamientos de control.', type: 'material', rarity: 'rare', weightKg: 0.1, baseValue: 20, stackable: true, maxStack: 99, obtainedFrom: 'Mine en cuevas glaciares, lagos subterráneos y ríos de montaña.', consumeIdea: 'Encantamientos de hielo y focos de control mental.', sideEffects: 'Enfría el entorno si se acumulan muchas.' },
  { name: 'Emerald', emoji: '💚', description: 'Gema verde de la naturaleza. Potencia magia druídica y venenos.', type: 'material', rarity: 'epic', weightKg: 0.1, baseValue: 40, stackable: true, maxStack: 99, obtainedFrom: 'Mine en bosques profundos y cuevas cubiertas de musgo.', consumeIdea: 'Focos druídicos, venenos potentes y joyas de la naturaleza.', sideEffects: 'Puede atraer insectos y pequeñas bestias.' },
  { name: 'Diamond', emoji: '💠', description: 'Diamante puro de extraordinario valor. Foco de energía inagotable.', type: 'material', rarity: 'legendary', weightKg: 0.1, baseValue: 100, stackable: true, maxStack: 99, obtainedFrom: 'Mine en las profundidades más oscuras de cuevas legendarias.', consumeIdea: 'Foco de poder para armas y artefactos legendarios.', sideEffects: 'Atrae codicia; puede causar conflictos entre aventureros.' },
  { name: 'Void Crystal', emoji: '🌌', description: 'Cristal nacido del vacío. Contiene energía inestable y peligrosa.', type: 'material', rarity: 'legendary', weightKg: 0.2, baseValue: 130, stackable: true, maxStack: 99, obtainedFrom: 'Mine en grietas del vacío y ruinas de civilizaciones caídas.', consumeIdea: 'Alimentar artefactos de poder inmenso y portales.', sideEffects: 'Inestable; puede desgarrar pequeños objetos cercanos.' },

  // ========== COMIDA Y BEBIDA ==========
  { name: 'Raw Meat', emoji: '🥩', description: 'Carne cruda de caza. Se cocina para recuperar HP.', type: 'material', rarity: 'common', weightKg: 0.5, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Drop de casi toda la fauna salvaje.', consumeIdea: 'Cocinar en fuego para crear alimento seguro y nutritivo.', sideEffects: 'Consumir cruda puede causar enfermedades.' },
  { name: 'Cooked Meat', emoji: '🍖', description: 'Carne asada que recupera HP. Efecto básico de curación.', type: 'consumable', rarity: 'common', weightKg: 0.4, usable: true, effectType: 'hp', effectValue: 12, baseValue: 4, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con Raw Meat y fuego/carbón.', consumeIdea: 'Comer para recuperar salud y saciar el hambre.', sideEffects: 'Ninguno.' },
  { name: 'Berry', emoji: '🫐', description: 'Baya silvestre dulce. Recupera un poco de STA.', type: 'consumable', rarity: 'common', weightKg: 0.05, usable: true, effectType: 'sta', effectValue: 3, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Gather en bosques y llanuras durante el día.', consumeIdea: 'Comer como tentempié rápido.', sideEffects: 'Mancha dedos y ropa.' },
  { name: 'Honey', emoji: '🍯', description: 'Miel natural. Recupera HP lentamente durante un tiempo.', type: 'consumable', rarity: 'uncommon', weightKg: 0.3, usable: true, effectType: 'hp', effectValue: 8, baseValue: 5, stackable: true, maxStack: 99, obtainedFrom: 'Gather en colmenas salvajes de bosques y praderas.', consumeIdea: 'Comer para regeneración gradual de salud.', sideEffects: 'Atrae insectos si se derrama.' },
  { name: 'Bread', emoji: '🍞', description: 'Pan básico. Aumenta ligeramente la regeneración de STA.', type: 'consumable', rarity: 'common', weightKg: 0.3, usable: true, effectType: 'sta', effectValue: 10, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con trigo y agua, o comprar en pueblos.', consumeIdea: 'Comer para recuperar resistencia de forma sostenida.', sideEffects: 'Ninguno.' },
  { name: 'Cheese', emoji: '🧀', description: 'Queso curado. Recupera HP y mejora el ánimo.', type: 'consumable', rarity: 'common', weightKg: 0.2, usable: true, effectType: 'hp', effectValue: 7, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con leche o comprar en mercados.', consumeIdea: 'Comer para una curación rápida y ligera.', sideEffects: 'Puede causar sed.' },
  { name: 'Wine', emoji: '🍷', description: 'Vino tinto. Recupera STA pero reduce ligeramente la precisión.', type: 'consumable', rarity: 'uncommon', weightKg: 0.5, usable: true, effectType: 'sta', effectValue: 20, baseValue: 6, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con uvas o comprar en tabernas.', consumeIdea: 'Beber para relajar los nervios y recuperar energía.', sideEffects: 'Reduce precisión un 3% durante 2 min.' },
  { name: 'Ale', emoji: '🍺', description: 'Cerveza fuerte. Recupera STA y da coraje, pero baja evasión.', type: 'consumable', rarity: 'common', weightKg: 0.5, usable: true, effectType: 'sta', effectValue: 14, baseValue: 4, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con cereales o comprar en tabernas.', consumeIdea: 'Beber para coraje en combate y recuperar vigor.', sideEffects: 'Reduce evasión un 2% durante 2 min.' },

  // ========== POCIONES Y CONSUMIBLES ESPECIALES ==========
  { name: 'Small Health Potion', emoji: '🧪', description: 'Poción roja pequeña. Recupera 25 HP al instante.', type: 'consumable', rarity: 'common', weightKg: 0.3, usable: true, effectType: 'hp', effectValue: 25, baseValue: 8, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con hierbas y agua, o comprar a alquimistas.', consumeIdea: 'Beber en combate para curación rápida.', sideEffects: 'Sabor metálico.' },
  { name: 'Health Potion', emoji: '❤️', description: 'Poción de curación estándar. Recupera 50 HP.', type: 'consumable', rarity: 'uncommon', weightKg: 0.3, usable: true, effectType: 'hp', effectValue: 50, baseValue: 18, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con Bloodroot, hierbas y frascos.', consumeIdea: 'Beber para una curación media en combate.', sideEffects: 'Ninguno.' },
  { name: 'Greater Health Potion', emoji: '🩸', description: 'Poción de curación superior. Recupera 100 HP.', type: 'consumable', rarity: 'rare', weightKg: 0.3, usable: true, effectType: 'hp', effectValue: 100, baseValue: 45, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con Champiñón Mágico, Bloodroot y agua bendita.', consumeIdea: 'Beber para recuperación masiva de salud.', sideEffects: 'Puede causar somnolencia leve tras el efecto.' },
  { name: 'Small Stamina Potion', emoji: '🧪', description: 'Poción azul pequeña. Recupera 30 STA.', type: 'consumable', rarity: 'common', weightKg: 0.3, usable: true, effectType: 'sta', effectValue: 30, baseValue: 6, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con hierbas y esencia de agua.', consumeIdea: 'Beber para recuperar resistencia rápidamente.', sideEffects: 'Ninguno.' },
  { name: 'Stamina Potion', emoji: '🔵', description: 'Poción de energía estándar. Recupera 60 STA.', type: 'consumable', rarity: 'uncommon', weightKg: 0.3, usable: true, effectType: 'sta', effectValue: 60, baseValue: 15, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con Moonpetal y esencia de agua.', consumeIdea: 'Beber para una gran inyección de vigor.', sideEffects: 'Ligero temblor durante 30 segundos.' },
  { name: 'Antidote', emoji: '💊', description: 'Poción verde que elimina veneno y otros efectos químicos.', type: 'consumable', rarity: 'uncommon', weightKg: 0.2, usable: true, effectType: 'cleanse', effectValue: 1, baseValue: 12, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con Wolfsbane, hierbas y agua.', consumeIdea: 'Beber para limpiar venenos y ácidos.', sideEffects: 'Sabor amargo intenso.' },
  { name: 'Fire Resistance Potion', emoji: '🔥', description: 'Poción roja-anaranjada. Aumenta resistencia elemental durante 10 min.', type: 'consumable', rarity: 'rare', weightKg: 0.3, usable: true, effectType: 'buff', effectValue: 15, baseValue: 28, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con Sulfur, Topaz y agua volcánica.', consumeIdea: 'Beber antes de entrar en zonas volcánicas o enfrentar dragones.', sideEffects: 'Piel ligeramente cálida al tacto.' },
  { name: 'Shadow Elixir', emoji: '🌑', description: 'Elixir oscuro. Aumenta evasión pero reduce ligeramente HP máx.', type: 'consumable', rarity: 'epic', weightKg: 0.3, usable: true, effectType: 'buff', effectValue: 20, baseValue: 55, stackable: true, maxStack: 10, obtainedFrom: 'Craftear con Essence of Shadow, Ghostcap y alcohol fuerte.', consumeIdea: 'Beber para fundirse con las sombras durante el combate.', sideEffects: 'Reduce HP máxima un 5% durante la duración.' },
  { name: 'Toxic Vial', emoji: '☠️', description: 'Frasco de veneno concentrado. Daña al enemigo con el tiempo.', type: 'consumable', rarity: 'rare', weightKg: 0.3, usable: true, effectType: 'damage', effectValue: 30, baseValue: 35, stackable: true, maxStack: 20, obtainedFrom: 'Craftear con Venom Sac, Nightshade y aceite.', consumeIdea: 'Lanzar contra enemigos para aplicar daño prolongado.', sideEffects: 'Riesgo de autoexposición si se rompe cerca del usuario.' },

  // ========== VARIOS Y REACTIVOS ==========
  { name: 'Feather', emoji: '🪶', description: 'Pluma ligera de ave. Usada para flechas y pergaminos.', type: 'material', rarity: 'common', weightKg: 0.01, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Drop de aves pequeñas y criaturas aladas.', consumeIdea: 'Empenachar flechas y escribir pergaminos ligeros.', sideEffects: 'Ninguno.' },
  { name: 'Beeswax', emoji: '🕯️', description: 'Cera de abeja. Usada para velas, sellos y acabados.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Gather en colmenas junto con miel.', consumeIdea: 'Fabricar velas, sellos y acabados protectores.', sideEffects: 'Se derrite con el calor.' },
  { name: 'Salt', emoji: '🧂', description: 'Sal mineral. Conservante y catalizador alquímico básico.', type: 'material', rarity: 'common', weightKg: 0.1, baseValue: 1, stackable: true, maxStack: 99, obtainedFrom: 'Mine en yacimientos salinos y orillas de lagos secos.', consumeIdea: 'Conservar alimentos, curtir pieles y catalizar mezclas.', sideEffects: 'En exceso seca la piel.' },
  { name: 'Oil', emoji: '🛢️', description: 'Aceite vegetal o mineral. Lubricante, combustible y componente de pociones.', type: 'material', rarity: 'common', weightKg: 0.4, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con semillas o gather en manantiales de petróleo menor.', consumeIdea: 'Lubricar mecanismos, alimentar lámparas y pociones.', sideEffects: 'Inflamable.' },
  { name: 'Ink', emoji: '🖋️', description: 'Tinta oscura para escribir pergaminos y mapas.', type: 'material', rarity: 'common', weightKg: 0.2, baseValue: 3, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con carbón, agua y goma.', consumeIdea: 'Escribir pergaminos, mapas y contratos.', sideEffects: 'Mancha permanentemente la ropa.' },
  { name: 'Parchment', emoji: '📜', description: 'Hoja de pergamino preparada. Base para pergaminos mágicos.', type: 'material', rarity: 'common', weightKg: 0.05, baseValue: 2, stackable: true, maxStack: 99, obtainedFrom: 'Craftear con piel curtida o comprar en escribas.', consumeIdea: 'Base de pergaminos mágicos y mapas.', sideEffects: 'Ninguno.' },
];

async function main() {
  console.log('Seeding resources...');
  for (const res of RESOURCES) {
    await prisma.resource.upsert({
      where: { name: res.name },
      update: res,
      create: res,
    });
  }
  console.log(`Seeded ${RESOURCES.length} resources.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
